### ISSUE TITLE
支持.net4.8

### ISSUE THREAD

**Issue by FreeVB** [AZhrZho/ECharts.Net#23]
请问会考虑支持.net4.8这样非 Core核心吗？

**Comment by asine** [comment]
同问

**Comment by AZhrZho** [comment]
感谢关注。目前的开发计划是先基于.net core完成开发，再移植到.net framework

**Comment by FreeVB** [comment]
好的，谢谢回复。

**Comment by AZhrZho** [comment]
最新版本v0.0.4已添加对.net framework的支持，最低版本4.6.2

**Comment by FreeVB** [comment]
牛呀！这么快就实现了，虽然要手工修改一些，但还是可以实现的。
