### ISSUE TITLE
不使用WebView2

### ISSUE THREAD

**Issue by FreeVB** [AZhrZho/ECharts.Net#28]
请问有不使用WebView2的方法没？
我想尽可能的不引用额外的库和使用包，这样编译后就可以只需要一个DLL就可以了。
（我把现在所有的项目合并到 ECharts.Net 中了）

**Comment by AZhrZho** [comment]
WebView2在Windows11中为系统组件，如果使用其他webview，反而会引入更多依赖。
如果你是想把webview2sdk的dll也打包进单一dll或exe，可以看一下Costura.Fody这个项目
