### ISSUE TITLE
ASP mvc core sample 

### ISSUE THREAD

**Issue by fasteddys** [AZhrZho/ECharts.Net#8]
Hello this is great, can you please also include a simple sample on using this on the MVC page in ASP Core, so we can develop on it.

**Comment by AZhrZho** [comment]
Hi, I'm not sure what you referred to. If you are saying "Razor Pages" or "MVC", you can directly use ECharts as its a JavaScript library. I'm not good at writing web pages, here comes a very basic sample, based on "ASP.Net Core Web App" template:

Index.cshtml:

``` js
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js"></script>
<div id="chartDemo" style="width: 400px; height: 400px"></div>
<script>
   let option = {
      xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
      },
      yAxis: {
        type: 'value'
      },
      series: [
        {
          data: [150, 230, 224, 218, 135, 147, 260],
          type: 'line'
        }
      ]
    }
    var myChart = echarts.init(document.getElementById('chartDemo'))
    myChart.setOption(option)
</script>
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
``` 

![image](https://github.com/AZhrZho/ECharts.Net/assets/25339545/abfe2007-ab64-42f2-948e-8c0096f6fd66)

more details about ECharts: https://echarts.apache.org/en/index.html

Hope the above can help you.
